name: Build

on:
  push:
    branches:
      - master
      - release


jobs:
  static-inspect:
    name: Static Inspect
    runs-on: ubuntu-latest
    steps:
      - name: Runner checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        id: install
        run: |
          pip install ruff
          pip install mypy
          pip install bandit

      - name: Run inspection
        id: static-inspection
        run: |
          ruff check .
          ruff format --check .
          mypy .
          bandit -r . -ll

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Runner checkout
        uses: actions/checkout@v4

      - name: Extract app-version
        id: extract
        run: |
          APP_NAME=$(jq -r '.name' app-version.json)
          APP_VERSION=$(jq -r '.version' app-version.json)

          echo "name=$APP_NAME" >> GITHUB_OUTPUT
          echo "version=$APP_VERSION" >> GITHUB_OUTPUT
      
      - name: Build
        run: |
          APP_NAME="${{ steps.extract.outputs.name }}"
          APP_VERSION="{{ steps.extract.outputs.version }}"

          docker build -t "$APP_NAME:$APP_VERSION" 